### PR TITLE
Adds a new app setting (enableFileSystemMonitoring:bool) to specify w…

### PR DESCRIPTION
**Pull request by niklaskallander**
…hether file system monitoring should be enabled for the nuget server

### CODE REVIEW

**Comment by niklaskallander** [comment]
I can definitely improve the comment in the config file to explain this. 

However, isn't it called at least once an hour by `RebuildPackageStore` (called by one of the background tasks using a `Timer`)? 

The call chain looks like `RebuildPackageStore`->`AddPackagesFromDropFolder`->`OptimizedZipPackage.PurgeCache`, at least as far as I can see.

**Comment by xavierdecoster** [comment]
True that, still purges once an hour when background tasks enabled.

**Comment by niklaskallander** [comment]
Is that sufficient? I can still improve the comment, if you find it necessary.

Thanks! (:

**Comment by xavierdecoster** [comment]
Servers with lots of ingress might have noticeable impact on disk size growth by disabling the file system watcher.
I'd make a note along the lines of:

```
<!-- Disabling file system monitoring may result in increased storage capacity requirements as package cache may only be purged by a background job running on a fixed 1-hour interval. -->
```

**Comment by niklaskallander** [comment]
Thanks, I've modified the comment as requested. (:

**Comment by skofman1** [comment]
LGTM. @xavierdecoster , ok to merge?

**Comment by xavierdecoster** [comment]
Thanks for the contribution @niklaskallander !

**Pull request merged**
